import React from 'react';
import { motion } from 'framer-motion';

export const Privacy = () => {
    return (
        <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="pt-32 pb-20 px-6 max-w-4xl mx-auto min-h-screen"
        >
            <h1 className="text-4xl md:text-5xl font-bold text-cod-gray mb-8">Privacy Policy</h1>

            <div className="space-y-6 text-lg text-cod-gray/80 leading-relaxed">
                <p>Last Updated: December 2025</p>

                <section>
                    <h2 className="text-2xl font-bold text-cod-gray mb-4">1. Data Collection</h2>
                    <p>The Farmers Company ("we", "us") collects data generated by our autonomous vehicles (Scout, Care, Harvest) to improve agricultural outcomes. This includes soil data, crop health imagery, and environmental metrics.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-cod-gray mb-4">2. Usage of Information</h2>
                    <p>We use this data to:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>Create digital twins of orchards.</li>
                        <li>Optimize autonomous navigation paths.</li>
                        <li>Provide agronomic insights to the platform users.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-cod-gray mb-4">3. Data Security</h2>
                    <p>All gathered data is encrypted at rest and in transit. We employ industry-standard security protocols to protect your farm's proprietary information.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-cod-gray mb-4">4. Contact Us</h2>
                    <p>If you have questions about this policy, please contact us at privacy@thefarmerscompany.com.</p>
                </section>
            </div>
        </motion.div>
    );
};
